# USDF to NERSC workflow
flow_id: 5ec101ea-18b4-4251-84e6-645148ebe098
flow_function_id: 68630205-b679-4d2c-b284-b6cd7e75a674
# USDF is the compute site.
compute_endpoint_id: ac73ee3a-3f2e-425c-b618-f0079c953e4f
compute_collection_id: 31f8393f-79ef-4da4-a395-7127edd9b3a4
compute_base_path: /sdf/home/j/jchiang/rubin-user/DESC/globus_flow_test/
# NERSC is the repository site where results will be written.
repository_collection_id: 6bdc7956-fc0f-4ad2-989c-7aa5ee643a79  # NERSC
repository_base_path: /pscratch/sd/j/jchiang8/globus_flow_test/
payload_data:
   weekly: w_2026_03
   inputs_folder: test_repo
   outputs_folder: test_repo
